### ISSUE TITLE
Levenshtein algorithm error

### ISSUE THREAD

**Issue by comex** [autozimu/StringMetric.swift#4]
In this line of `distanceLevenshtein`:
```swift
                let cost = self[j] == target[j] ? 0 : 1
```
`self[j]` should probably be `self[i]`.  As is, the function gives incorrect results.

**Comment by autozimu** [comment]
Thanks. Resolved in release [0.2.1](https://github.com/autozimu/StringMetric.swift/releases/tag/0.2.1)
